version: '3'

services:

  db:
    image: mysql:8.0

    container_name: backend_agro_db

    restart: always

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend_agro

    volumes:
      - ./mysql_data:/var/lib/mysql